/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/Layout/AppBar.vue')['default']
    AttendanceChart: typeof import('./src/components/Charts/AttendanceChart.vue')['default']
    ConfirmDialog: typeof import('./src/components/Dialogs/ConfirmDialog.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    LoadingSpinner: typeof import('./src/components/Common/LoadingSpinner.vue')['default']
    NotificationContainer: typeof import('./src/components/Common/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/Common/SearchFilter.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    StudentForm: typeof import('./src/components/Dialogs/StudentForm.vue')['default']
    UserForm: typeof import('./src/components/Dialogs/UserForm.vue')['default']
  }
}
