<?php
namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $students = [
            // Grade 1 - Section A
            [
                'student_id' => 'STU2024001',
                'name' => 'Alice Johnson',
                'email' => 'alice.johnson@student.com',
                'class' => 'Grade 1',
                'section' => 'A',
                'roll_number' => '1',
                'date_of_birth' => '2017-03-15',
                'gender' => 'female',
                'parent_name' => 'Robert Johnson',
                'parent_email' => 'robert@parent.com',
                'parent_phone' => '+1234567894',
                'address' => '123 Main Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024002',
                'name' => 'Bob Smith',
                'email' => 'bob.smith@student.com',
                'class' => 'Grade 1',
                'section' => 'A',
                'roll_number' => '2',
                'date_of_birth' => '2017-05-20',
                'gender' => 'male',
                'parent_name' => 'Mary Smith',
                'parent_email' => 'mary.smith@parent.com',
                'parent_phone' => '+1234567896',
                'address' => '456 Oak Avenue, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024003',
                'name' => 'Carol Davis',
                'email' => 'carol.davis@student.com',
                'class' => 'Grade 1',
                'section' => 'A',
                'roll_number' => '3',
                'date_of_birth' => '2017-07-10',
                'gender' => 'female',
                'parent_name' => 'James Davis',
                'parent_email' => 'james.davis@parent.com',
                'parent_phone' => '+1234567897',
                'address' => '789 Pine Road, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024011',
                'name' => 'Daniel Wilson',
                'email' => 'daniel.wilson@student.com',
                'class' => 'Grade 1',
                'section' => 'A',
                'roll_number' => '4',
                'date_of_birth' => '2017-01-18',
                'gender' => 'male',
                'parent_name' => 'Sarah Wilson',
                'parent_email' => 'sarah.wilson@parent.com',
                'parent_phone' => '+1234567810',
                'address' => '321 Maple Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024012',
                'name' => 'Emma Brown',
                'email' => 'emma.brown@student.com',
                'class' => 'Grade 1',
                'section' => 'A',
                'roll_number' => '5',
                'date_of_birth' => '2017-09-22',
                'gender' => 'female',
                'parent_name' => 'Michael Brown',
                'parent_email' => 'michael.brown@parent.com',
                'parent_phone' => '+1234567811',
                'address' => '654 Cedar Avenue, City, State',
                'is_active' => true,
            ],

            // Grade 1 - Section B
            [
                'student_id' => 'STU2024004',
                'name' => 'David Wilson',
                'email' => 'david.wilson@student.com',
                'class' => 'Grade 1',
                'section' => 'B',
                'roll_number' => '1',
                'date_of_birth' => '2017-02-28',
                'gender' => 'male',
                'parent_name' => 'Lisa Wilson',
                'parent_email' => 'lisa@parent.com',
                'parent_phone' => '+1234567895',
                'address' => '321 Elm Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024005',
                'name' => 'Eva Brown',
                'email' => 'eva.brown@student.com',
                'class' => 'Grade 1',
                'section' => 'B',
                'roll_number' => '2',
                'date_of_birth' => '2017-04-12',
                'gender' => 'female',
                'parent_name' => 'Thomas Brown',
                'parent_email' => 'thomas.brown@parent.com',
                'parent_phone' => '+1234567898',
                'address' => '654 Maple Drive, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024013',
                'name' => 'Frank Miller',
                'email' => 'frank.miller@student.com',
                'class' => 'Grade 1',
                'section' => 'B',
                'roll_number' => '3',
                'date_of_birth' => '2017-11-05',
                'gender' => 'male',
                'parent_name' => 'Jennifer Miller',
                'parent_email' => 'jennifer.miller@parent.com',
                'parent_phone' => '+1234567812',
                'address' => '987 Oak Lane, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024014',
                'name' => 'Grace Taylor',
                'email' => 'grace.taylor@student.com',
                'class' => 'Grade 1',
                'section' => 'B',
                'roll_number' => '4',
                'date_of_birth' => '2017-12-30',
                'gender' => 'female',
                'parent_name' => 'Paul Taylor',
                'parent_email' => 'paul.taylor@parent.com',
                'parent_phone' => '+1234567813',
                'address' => '147 Pine Street, City, State',
                'is_active' => true,
            ],

            // Grade 2 - Section A
            [
                'student_id' => 'STU2024006',
                'name' => 'Henry Anderson',
                'email' => 'henry.anderson@student.com',
                'class' => 'Grade 2',
                'section' => 'A',
                'roll_number' => '1',
                'date_of_birth' => '2016-08-25',
                'gender' => 'male',
                'parent_name' => 'Nancy Anderson',
                'parent_email' => 'nancy.anderson@parent.com',
                'parent_phone' => '+1234567899',
                'address' => '987 Cedar Lane, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024007',
                'name' => 'Ivy Martinez',
                'email' => 'ivy.martinez@student.com',
                'class' => 'Grade 2',
                'section' => 'A',
                'roll_number' => '2',
                'date_of_birth' => '2016-11-30',
                'gender' => 'female',
                'parent_name' => 'Paul Martinez',
                'parent_email' => 'paul.martinez@parent.com',
                'parent_phone' => '+1234567800',
                'address' => '147 Birch Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024015',
                'name' => 'Jack Thomas',
                'email' => 'jack.thomas@student.com',
                'class' => 'Grade 2',
                'section' => 'A',
                'roll_number' => '3',
                'date_of_birth' => '2016-03-14',
                'gender' => 'male',
                'parent_name' => 'Maria Thomas',
                'parent_email' => 'maria.thomas@parent.com',
                'parent_phone' => '+1234567814',
                'address' => '258 Walnut Road, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024016',
                'name' => 'Katherine Lee',
                'email' => 'katherine.lee@student.com',
                'class' => 'Grade 2',
                'section' => 'A',
                'roll_number' => '4',
                'date_of_birth' => '2016-06-19',
                'gender' => 'female',
                'parent_name' => 'David Lee',
                'parent_email' => 'david.lee@parent.com',
                'parent_phone' => '+1234567815',
                'address' => '369 Spruce Avenue, City, State',
                'is_active' => true,
            ],

            // Grade 2 - Section B
            [
                'student_id' => 'STU2024017',
                'name' => 'Liam Garcia',
                'email' => 'liam.garcia@student.com',
                'class' => 'Grade 2',
                'section' => 'B',
                'roll_number' => '1',
                'date_of_birth' => '2016-01-15',
                'gender' => 'male',
                'parent_name' => 'Anna Garcia',
                'parent_email' => 'anna.garcia@parent.com',
                'parent_phone' => '+1234567816',
                'address' => '741 Elm Drive, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024018',
                'name' => 'Mia Rodriguez',
                'email' => 'mia.rodriguez@student.com',
                'class' => 'Grade 2',
                'section' => 'B',
                'roll_number' => '2',
                'date_of_birth' => '2016-04-22',
                'gender' => 'female',
                'parent_name' => 'Carlos Rodriguez',
                'parent_email' => 'carlos.rodriguez@parent.com',
                'parent_phone' => '+1234567817',
                'address' => '852 Oak Street, City, State',
                'is_active' => true,
            ],

            // Grade 3 - Section A
            [
                'student_id' => 'STU2024008',
                'name' => 'Noah Hernandez',
                'email' => 'noah.hernandez@student.com',
                'class' => 'Grade 3',
                'section' => 'A',
                'roll_number' => '1',
                'date_of_birth' => '2015-01-15',
                'gender' => 'male',
                'parent_name' => 'Susan Hernandez',
                'parent_email' => 'susan.hernandez@parent.com',
                'parent_phone' => '+1234567801',
                'address' => '258 Walnut Avenue, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024009',
                'name' => 'Olivia Martinez',
                'email' => 'olivia.martinez@student.com',
                'class' => 'Grade 3',
                'section' => 'A',
                'roll_number' => '2',
                'date_of_birth' => '2015-06-22',
                'gender' => 'female',
                'parent_name' => 'Carlos Martinez',
                'parent_email' => 'carlos.martinez@parent.com',
                'parent_phone' => '+1234567802',
                'address' => '369 Spruce Road, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024010',
                'name' => 'Peter Thomas',
                'email' => 'peter.thomas@student.com',
                'class' => 'Grade 3',
                'section' => 'A',
                'roll_number' => '3',
                'date_of_birth' => '2015-09-08',
                'gender' => 'male',
                'parent_name' => 'Maria Thomas',
                'parent_email' => 'maria.thomas@parent.com',
                'parent_phone' => '+1234567803',
                'address' => '741 Oak Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024019',
                'name' => 'Quinn Johnson',
                'email' => 'quinn.johnson@student.com',
                'class' => 'Grade 3',
                'section' => 'A',
                'roll_number' => '4',
                'date_of_birth' => '2015-12-12',
                'gender' => 'male',
                'parent_name' => 'Rachel Johnson',
                'parent_email' => 'rachel.johnson@parent.com',
                'parent_phone' => '+1234567818',
                'address' => '963 Maple Lane, City, State',
                'is_active' => true,
            ],

            // Grade 3 - Section B
            [
                'student_id' => 'STU2024020',
                'name' => 'Ruby Smith',
                'email' => 'ruby.smith@student.com',
                'class' => 'Grade 3',
                'section' => 'B',
                'roll_number' => '1',
                'date_of_birth' => '2015-02-28',
                'gender' => 'female',
                'parent_name' => 'John Smith',
                'parent_email' => 'john.smith@parent.com',
                'parent_phone' => '+1234567819',
                'address' => '159 Cedar Street, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024021',
                'name' => 'Samuel Davis',
                'email' => 'samuel.davis@student.com',
                'class' => 'Grade 3',
                'section' => 'B',
                'roll_number' => '2',
                'date_of_birth' => '2015-07-17',
                'gender' => 'male',
                'parent_name' => 'Lisa Davis',
                'parent_email' => 'lisa.davis@parent.com',
                'parent_phone' => '+1234567820',
                'address' => '753 Pine Avenue, City, State',
                'is_active' => true,
            ],

            // Grade 4 - Section A
            [
                'student_id' => 'STU2024022',
                'name' => 'Taylor Wilson',
                'email' => 'taylor.wilson@student.com',
                'class' => 'Grade 4',
                'section' => 'A',
                'roll_number' => '1',
                'date_of_birth' => '2014-03-08',
                'gender' => 'female',
                'parent_name' => 'Mark Wilson',
                'parent_email' => 'mark.wilson@parent.com',
                'parent_phone' => '+1234567821',
                'address' => '357 Birch Road, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024023',
                'name' => 'Uma Brown',
                'email' => 'uma.brown@student.com',
                'class' => 'Grade 4',
                'section' => 'A',
                'roll_number' => '2',
                'date_of_birth' => '2014-08-25',
                'gender' => 'female',
                'parent_name' => 'Kevin Brown',
                'parent_email' => 'kevin.brown@parent.com',
                'parent_phone' => '+1234567822',
                'address' => '486 Elm Lane, City, State',
                'is_active' => true,
            ],

            // Grade 4 - Section B
            [
                'student_id' => 'STU2024024',
                'name' => 'Victor Miller',
                'email' => 'victor.miller@student.com',
                'class' => 'Grade 4',
                'section' => 'B',
                'roll_number' => '1',
                'date_of_birth' => '2014-01-30',
                'gender' => 'male',
                'parent_name' => 'Sarah Miller',
                'parent_email' => 'sarah.miller@parent.com',
                'parent_phone' => '+1234567823',
                'address' => '624 Oak Drive, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024025',
                'name' => 'Wendy Taylor',
                'email' => 'wendy.taylor@student.com',
                'class' => 'Grade 4',
                'section' => 'B',
                'roll_number' => '2',
                'date_of_birth' => '2014-05-14',
                'gender' => 'female',
                'parent_name' => 'Richard Taylor',
                'parent_email' => 'richard.taylor@parent.com',
                'parent_phone' => '+1234567824',
                'address' => '795 Maple Street, City, State',
                'is_active' => true,
            ],

            // Grade 5 - Section A
            [
                'student_id' => 'STU2024026',
                'name' => 'Xavier Anderson',
                'email' => 'xavier.anderson@student.com',
                'class' => 'Grade 5',
                'section' => 'A',
                'roll_number' => '1',
                'date_of_birth' => '2013-09-20',
                'gender' => 'male',
                'parent_name' => 'Michelle Anderson',
                'parent_email' => 'michelle.anderson@parent.com',
                'parent_phone' => '+1234567825',
                'address' => '138 Cedar Avenue, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024027',
                'name' => 'Yara Garcia',
                'email' => 'yara.garcia@student.com',
                'class' => 'Grade 5',
                'section' => 'A',
                'roll_number' => '2',
                'date_of_birth' => '2013-12-05',
                'gender' => 'female',
                'parent_name' => 'Roberto Garcia',
                'parent_email' => 'roberto.garcia@parent.com',
                'parent_phone' => '+1234567826',
                'address' => '279 Pine Road, City, State',
                'is_active' => true,
            ],

            // Grade 5 - Section B
            [
                'student_id' => 'STU2024028',
                'name' => 'Zane Rodriguez',
                'email' => 'zane.rodriguez@student.com',
                'class' => 'Grade 5',
                'section' => 'B',
                'roll_number' => '1',
                'date_of_birth' => '2013-04-18',
                'gender' => 'male',
                'parent_name' => 'Elena Rodriguez',
                'parent_email' => 'elena.rodriguez@parent.com',
                'parent_phone' => '+1234567827',
                'address' => '462 Birch Lane, City, State',
                'is_active' => true,
            ],
            [
                'student_id' => 'STU2024029',
                'name' => 'Ava Hernandez',
                'email' => 'ava.hernandez@student.com',
                'class' => 'Grade 5',
                'section' => 'B',
                'roll_number' => '2',
                'date_of_birth' => '2013-07-22',
                'gender' => 'female',
                'parent_name' => 'Jose Hernandez',
                'parent_email' => 'jose.hernandez@parent.com',
                'parent_phone' => '+1234567828',
                'address' => '583 Walnut Street, City, State',
                'is_active' => true,
            ],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }

        $this->command->info('Students created successfully!');
        $this->command->info('Total students: ' . count($students));
    }
}
